sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mnabeelanwer/frontend_web1 -f Dockerfile.dev .

script:
  - docker run -e CI=true mnabeelanwer/frontend_web1 npm run test
